version: '2'
services:
  arstotzka:
    build: .
    container_name: arstotzka
    working_dir: /home/app/app
    volumes:
      - .:/home/app/app
    command: /bin/bash -c 'bundle install && bundle exec rspec'
