version: '3'
services:
  base: &base
    build: .
    working_dir: /home/app/app
    volumes:
      - .:/home/app/app

  #################### CONTAINERS ####################

  arstotzka:
    <<: *base
    container_name: arstotzka
    command: /bin/bash -c 'rspec'

  test_all:
    <<: *base
    command: /bin/bash -c 'rspec && yard && rake yardstick_measure && rake verify_measurements'
