version: '2'
services:
  base: &base
    image: ruby:2.4.0
    working_dir: /home/app/arstotzka
    volumes:
      - .:/home/app/arstotzka
      - arstotzka_gems_2_4_0:/usr/local/bundle

  #################### CONTAINERS ####################

  arstotzka:
    <<: *base
    container_name: arstotzka
    command: /bin/bash -c 'bundle install && bundle exec rspec'

volumes:
  arstotzka_gems_2_4_0:
