version: 2
jobs:
  build:
    docker:
      - image: darthjee/circleci_ruby_240:0.2.2
    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: bundle install
      - run: bundle exec rspec
      - run: rubocop
      - run: ./cc-test-reporter after-build --exit-code $?
