threshold: 100
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude: []
  ReturnTag:
    enabled: true
    exclude:
      - Arstotzka::Crawler#block
      - Arstotzka::Crawler#options
      - Arstotzka::Exception::FetcherBuilderNotFound#attribute
      - Arstotzka::Exception::FetcherBuilderNotFound#klass
      - Arstotzka::Fetcher#options
      - Arstotzka::FetcherBuilder#options
      - Arstotzka::HashReader#options
      - Arstotzka::MethodBuilder#attr_names
      - Arstotzka::MethodBuilder#options
      - Arstotzka::Reader#keys
      - Arstotzka::Reader#options
      - Arstotzka::Wrapper#options
  Summary::Presence:
    enabled: true
    exclude:
      - Arstotzka::Crawler#block
      - Arstotzka::Crawler#options
      - Arstotzka::Exception::FetcherBuilderNotFound#attribute
      - Arstotzka::Exception::FetcherBuilderNotFound#klass
      - Arstotzka::Fetcher#options
      - Arstotzka::FetcherBuilder#options
      - Arstotzka::HashReader#options
      - Arstotzka::MethodBuilder#attr_names
      - Arstotzka::MethodBuilder#options
      - Arstotzka::Reader#keys
      - Arstotzka::Reader#options
      - Arstotzka::Wrapper#options
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
