threshold: 81.7
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude: []
  ReturnTag:
    enabled: true
    exclude:
      - Arstotzka::Builder#attr_names
      - Arstotzka::Builder#json_name
      - Arstotzka::Builder#path
      - Arstotzka::Builder#full_path
      - Arstotzka::Builder#cached
      - Arstotzka::Crawler#post_process
      - Arstotzka::Crawler#path
      - Arstotzka::Crawler#case_type
      - Arstotzka::Crawler#compact
      - Arstotzka::Crawler#default
      - Arstotzka::Fetcher#path
      - Arstotzka::Fetcher#hash
      - Arstotzka::Fetcher#instance
  Summary::Presence:
    enabled: true
    exclude:
      - Arstotzka::Builder#attr_names
      - Arstotzka::Builder#json_name
      - Arstotzka::Builder#path
      - Arstotzka::Builder#full_path
      - Arstotzka::Builder#cached
      - Arstotzka::Crawler#post_process
      - Arstotzka::Crawler#path
      - Arstotzka::Crawler#case_type
      - Arstotzka::Crawler#compact
      - Arstotzka::Crawler#default
      - Arstotzka::Fetcher#path
      - Arstotzka::Fetcher#hash
      - Arstotzka::Fetcher#instance
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
